### ISSUE TITLE
Create new site from template

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#1]
Leave the filler content in

create a gh-pages branch too please

due: 
8-5-15  2p

**Comment by rodneystrong** [comment]
In case I never told you where the clean template is, pull the code from this commit: 

https://github.com/EditLLC/client-sublime-time/commits/master

**Comment by purplyrocky** [comment]
done da1be3aecfb09493630c6c419b5e28dcb2df6656
http://editllc.github.io/client-wisescuba/
