### ISSUE TITLE
logo styleguide fix

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#13]
Hey Joel, 

 I created a video for feedback on the styleguide you created for the wise scuba logo. Please watch the video linked below and complete the fixes.

https://youtu.be/iM-JwpWfRKc

due:
9-10-15   3p

**Comment by jperez4509** [comment]
I have created and uploaded the two styleguides you requested. They are in the google drive https://drive.google.com/folderview?id=0B8EN2ZGYf3v5fmM3V043Mk1wWjZjM2ZQZ3NTTzNyMWcwbzV4ZmxNVUZLRS1tR2JoNGo3VU0&usp=sharing
