### ISSUE TITLE
Wise scuba style guide missing branding

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#14]
https://drive.google.com/open?id=0B8EN2ZGYf3v5ZlJjSXlCSnNsbjg

At the bottom you're missing a screenshot of the logo being used on a computer. 

Please add this as soon as you can because I plan to email the client with both style guides today.

due:
9-11-15  1p

**Comment by jperez4509** [comment]
In the copy I uploaded and that I have. I do see that both style guides have the computer with the image of the website and the logo. Can you send me a screen shot of what you see.
