### ISSUE TITLE
Add this testimonial

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#17]
WISE Scuba is an excellent place to either begin or further your scuba diving adventure.  From 

first time divers looking to get certified, to certified divers looking to gain more experience and 

education, WISE Scuba can do it.  

I began training with Kristin at WISE Scuba after already becoming certified with another 

instructor.  The confidence, competence and ability I have gained while diving with her is 

something that would probably have taken me many years to figure out on my own.  If you are 

looking for a more personal atmosphere to train in, this is the place to go.  Kristin places an 

emphasis on safety and education.  You will learn much more about diving than just what 

happens under the water, you will learn appreciation for the undersea environment as well as 

how to evaluate dive conditions and know when it is time to walk away from a dive.  If you put 

forth the effort, Kristin can make you more than just a scuba tourist, she can make you a diver 

that is comfortable and at home in the water.  I intend to continue my training with WISE Scuba 

and when my two children are of age, Kristin will be the one who trains them.  I can highly 

recommend Kristin and WISE Scuba as not only is she a great trainer, but she is also a great 

mentor and friend.  For first rate, personalized dive instruction, look no further than WISE 

Scuba.

Rob Blehm

There's no photo, so remove the default photo with nothing in it's place. Also, remove the other placeholder testimonials.

due:
10-14-15 11a

**Comment by vanderbeam** [comment]
@rodneystrong  I didn't think it was immediately obvious that that was a testimonial so I went ahead and added a section header. This is done.

**Comment by rodneystrong** [comment]
Excellent work, glad you took that initiative, i agree with the choice
