### ISSUE TITLE
Add this gcal embed somewhere

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#18]
Find a good spot to embed this calendar somewhere on the site

````
<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showTz=0&amp;height=600&amp;wkst=1&amp;bgcolor=%2366cccc&amp;src=gdu038hchk17ccv0srrfrhdo58%40group.calendar.google.com&amp;color=%230F4B38&amp;src=en.usa%23holiday%40group.v.calendar.google.com&amp;color=%232952A3&amp;ctz=America%2FLos_Angeles" style=" border:solid 1px #777 " width="800" height="600" frameborder="0" scrolling="no"></iframe>
````

My first thought would be to replace the "Our Process" section with this calendar, using the same background image.

due:
10-14-15    1p

**Comment by vanderbeam** [comment]
@rodneystrong It didn't look very good on that background at all and didn't make much sense just smacked in the middle of nowhere (though I assume this is in the very early stages of development so I know arrangement will probably change). The only place that it really made sense to me, assuming the Google calendar would list when all the classes was, was to put it under the classes section. It also looks much better on a white background.

**Comment by vanderbeam** [comment]
It's done though.

**Comment by rodneystrong** [comment]
*nods
Thanks for taking the time to think it through; I agree with the choice. 

Now comes the somewhat difficult part.  

Could you research ways to style the google calendar? Style it in a way that it matches closer with the theme of the website rather than look like it's clashing. At most, you may only be able to change the colors. Hopefully not. 

new due date:
10-15-15  3p

**Comment by vanderbeam** [comment]
I'm on it

**Comment by rodneystrong** [comment]
you're a boss

**Comment by vanderbeam** [comment]
@rodneystrong OK, so just an update.... after watching dozens of YouTube videos, reading a million articles, and crying a lot I figured out how style the Google Calendar.
I got it working and everything, but I need some information from you/the client (whoever is running the calendar). I'm not using the iframe. Basically, it's impossible to style it outside of the basic styling options in Google.  

1) I need their Google calendar API key
2) I need their Google Calendar Address (in the calendar settings)

I doing that actual styling (the easy part) right now. This should be done tonight. If you don't get the API key/address before I'm done I'll go ahead and push it (I made a test calendar on my own google account that I'm using as a filler) and if I'm not the one who update the information, everything is commented in the file so it shouldn't be a problem for anyone else to figure out. 

I'm totally saving this script for future projects!

**Comment by rodneystrong** [comment]
I'm so proud of you ... 

I'll follow up with the client about the API key. 

Could you please post the link to the documentation you found here please so I can review and translate the necessary language to convince the client of why we need their API key? Also, I have to understand how to instruct them on getting that API key as well. thaaank you

**Comment by vanderbeam** [comment]
I'm using a jQuery plugin called "Full Calendar"
Home page: http://fullcalendar.io/
Easy Instruction for the API key are also listed on the site: http://fullcalendar.io/docs/google_calendar/

**Comment by vanderbeam** [comment]
So here's the first draft. The rest of the site is really simple at the moment so I decided to go pretty simple with the design on the calendar so it didn't stand out like crazy. Made sure all the fonts and colours and corners and whatnot coincided with the rest of the site.

I am having an issue though and I was hoping I could outsource. You'll notice on the top left of the cal there are two grey span blocks. They are prev/next month control. For some reason I just CAN'T figure out how I changed this or how to alter it. I know it must be a simple fix but I think I may just be too close to the code at this point. Initially I was trying to replace it with the prev/next green arrows (in the img/calendar folder). 

Let me know what you think.

**Comment by rodneystrong** [comment]
holy shit meg. you did a GREAT job with the calendar. I was supposed to have a call today with the client but she missed it; rescheduled for tomorrow 4pm so i'll get feedback from her then.

**Comment by rodneystrong** [comment]
Just messaged you the API key in slack.

**Comment by rodneystrong** [comment]
Comment here when you've got the client's calendar embedded and no longer yours please.

**Comment by vanderbeam** [comment]
@rodneystrong In addition to the Calendar key, I need their calendar's link. 

- Go to Google Calendar
- Click the dropdown arrow never to the calendar you want to share and click "Calendar Settings"
- 7 items down, there is a line for "Calendar Address" Click the Orange XML button. 
- I need the address that's shown in the popup box.

**Comment by rodneystrong** [comment]
GREAT instructions. I imagine you copy/pasted them somewhere; so good choice.

https://calendar.google.com/calendar/feeds/wisescuba%40gmail.com/public/basic

**Comment by vanderbeam** [comment]
ಠ_ಠ I wrote them. I can be detailed when I want to you know! :P 

Thanks for the link!
