### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#2]
Create a logo for our client W.I.S.E. scuba. 

Most likely she'll want something more than just a type treatment logo. Try 3 different themes:

- casual

- professional

- playful

WISE stands for Western Institute of Submerged/Scuba Education 

Initial thoughts from her:

- I'd like a logo with a map (but then again a map doesn't convey scuba.. so it might not be best to use it)

Stuff from her:

This is the site she tried to create on weebly: http://wisescuba.weebly.com/

This is their facebook page: https://www.facebook.com/pages/WISE-SCUBA/1666389160249599?ref=bookmarks

due: 

8-16-15   3p

**Comment by jperez4509** [comment]
Hey Alex,

On Friday you said that I should upload the logos to the Google Drive folder for WISE, but I am unable to locate that folder. Can you help me out with letting me know where it is located?

**Comment by jperez4509** [comment]
Done.
