### ISSUE TITLE
Branding assets

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#21]
In your branding profile PDF, you have a section called "Alternative logos". Could you please export the one with just the word "Wise" and the letter "W" into 500 x 500px .png and .jpg please? 

Could you please do the same for the regular logo as well? Crop the regular logo so there is only a little white space on the sides of the logo. 

due:
11-18-15   3p

**Comment by rodneystrong** [comment]
Oh also, favicon of the "W" and maybe "W" with circle please. thaaaank you

**Comment by jperez4509** [comment]
All requested logos can be found in the google drive: https://drive.google.com/a/editllc.com/folderview?id=0B88_mCI0OTGkLVh1LUR6VUhCV2M&usp=sharing
