### ISSUE TITLE
Content for site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#3]
Go to this site and review how her 'events' were created/laid out: http://editllc.github.io/client-sublime-time/

Now go to this site and pull in the content and organize it the same way the 'events' are organized in the link above.

Also, put her facebook feed somewhere on the site. I'll leave it up to you where you think is best. 
https://www.facebook.com/pages/WISE-SCUBA/1666389160249599?ref=bookmarks

due:
8-21-15   8p

**Comment by purplyrocky** [comment]
@rodneystrong Which site am I supposed to pull the content from?

**Comment by rodneystrong** [comment]
@purplyrocky crap, so sorry. here's the square marketplace link: https://squareup.com/market/wise-scuba

**Comment by purplyrocky** [comment]
@rodneystrong The icons and prices are all on the page and i condensed a lot of the content down but i was wondering if i can add modals like they have on their squareup site? Even condensed down, it's too much content to add underneath the thumbnails like in the sublime time site. I can have all the modals done by the sunday night.

**Comment by rodneystrong** [comment]
hmm.. 

alright try it.

**Comment by purplyrocky** [comment]
sweet, I'll push the changes and close this issue and open a new one for the modals?

**Comment by rodneystrong** [comment]
right on, I approve

**Comment by purplyrocky** [comment]
Closing with this commit here f14dbafd9dfcd1a9f6936978030e0423be404ca1
Opening new issue for modals here https://github.com/EditLLC/client-wisescuba/issues/4

**Comment by purplyrocky** [comment]
I was trying to figure out why the facebook page plugin would not work when i pasted in the code, i found this on stackoverflow that says it does not work locally anymore
http://stackoverflow.com/questions/15669167/failed-to-load-resource-using-facebooks-example-code

I have included the code anyway under the "About" section

**Comment by rodneystrong** [comment]
You're amazing dude.. I knew you'd put in the time to figure it out.
