### ISSUE TITLE
Fix links in modals

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#5]
When you click on a scuba class and the modal pops up, the "add to basket" link doesn't take you to the square marketplace. 

Please make it so and have it go to the correct class the user initially clicked on.

due:
8-25-15    11p

**Comment by purplyrocky** [comment]
Could you please clear this up for me? I tried going to the square marketplace and inspecting the element for the "add to cart" button but the button does not have a link. I added an "a" tag inside the button to link to the store and added the button class like on the squareup site and it does not add to cart.

**Comment by purplyrocky** [comment]
Alright, I found a link that will take you to the individual product pages, I could use those but I have a few concerns. Should I change the text on the button to something else that way the user doesn't have to click, "Add to cart" twice? Also, the individual pages have those long descriptions from before I edited them down.

**Comment by rodneystrong** [comment]
Good questions, glad you asked them. 

I agree, so change your text to say "Purchase" instead of "Add to basket".

In terms of those pages having long descriptions: that's totally fine. If they got that far then they'll want to know as much of the class as possible before they shell out $100+.

**Comment by purplyrocky** [comment]
done 3dc2f9c1dfe38d44ca3dcfa4340e2c4fb5f08be6
