### ISSUE TITLE
create a logo sheet and export png's

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#7]
Thanks for uploading the .ai files. 

Could you please export all the individual logos as png's (with no background color) 

Also, could you please create a logo sheet for the new logos as well? Exactly the way you did it here: https://drive.google.com/open?id=0B8EN2ZGYf3v5NHlYSjVXSnoyYjg

due:
8-26-15   5p

**Comment by jperez4509** [comment]
Done
