### ISSUE TITLE
other images on site

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/client-wisescuba#9]
Again, if you go to her square marketplace link you'll see more images (many of which are used to represent the classes)

crop and put some of these images into the placeholders you see on the current site. 

due:
8-26-15   10p

**Comment by purplyrocky** [comment]
After using those images for the classes and choosing two for use in the slider, I was left with one image and a thumbnail. I cropped the image and added it to the page in place of that cityscape under "awesome features" section and resized the thumbnail and put in where the logo is supposed to go.
